"use client";
import { Headland_One, Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/header/page";
import "../../node_modules/bootstrap/dist/css/bootstrap.css";
// import { socketConnect } from "sockettwo";
import { useEffect } from "react";
const inter = Inter({ subsets: ["latin"] });

const metadata = {
  title: "Simple Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  // useEffect(() => {
  //   const handleScroll = () => {
  //     console.log("The window are scrolled!");
  //   };

  //   if (typeof window !== "undefined") {
  //     window.addEventListener("scroll", handleScroll);

  //     return () => {
  //       window.removeEventListener("scroll", handleScroll);
  //     };
  //   }
  // }, []);

  // console.log("hi");

  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css"
        ></link>
      </head>
      <body className={inter.className}>
        <div className="headerFix">
          <Header />
        </div>
        {children}
      </body>
    </html>
  );
}
